apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: foo
  namespace: apps
spec:
  releaseName: foo
  chart:
    spec:
      chart: podinfo
      version: "5.0.0"
      sourceRef:
        kind: HelmRepository
        name: foo
        namespace: apps
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    cache: redis-master.redis:6379
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      path: "/"

